/**
* event331-api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param oldPassword @IsDefined() @Length(6)
 * @param password @IsDefined() @Length(6)
 */
data class ChangeMyPasswordInput (
    /* @IsDefined() @Length(6) */
    val oldPassword: kotlin.String? = null,
    /* @IsDefined() @Length(6) */
    val password: kotlin.String? = null
) {

}

