/**
* event331-api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.6
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param imageId 
 * @param blobUrl 
 */
data class CreateImageOutput (
    val imageId: kotlin.Int? = null,
    val blobUrl: kotlin.String? = null
) {

}

