/**
* event331-api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.CommentDto
import io.swagger.client.models.ImageDto
import io.swagger.client.models.LatLng
import io.swagger.client.models.RatingDto

/**
 * 
 * @param id 
 * @param title 
 * @param latLng 
 * @param images 
 * @param comments 
 * @param ratings 
 */
data class HotelDto (
    val id: kotlin.Int? = null,
    val title: kotlin.String? = null,
    val latLng: LatLng? = null,
    val images: kotlin.Array<ImageDto>? = null,
    val comments: kotlin.Array<CommentDto>? = null,
    val ratings: kotlin.Array<RatingDto>? = null
) {

}

