/**
* event331-api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param sex 
 */
data class UserDto (
    val id: java.math.BigDecimal? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val sex: kotlin.Int? = null
) {

}

